### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by Zuiron** [Zuiron/Photosynthesis#80]
- [x] drop chance small trees, kwi grape.
- [x] fix fluid sided inventory, works on milk separator
- [x] skillet progress arrow
